# Phase 3 Step 3: AlertManager Configuration for SMETA360-2

global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@smeta360.com'
  smtp_auth_username: 'alerts@smeta360.com'
  smtp_auth_password: 'your-smtp-password'

route:
  group_by: ['alertname', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  
  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      repeat_interval: 5m

    # Warning alerts - less frequent notifications
    - match:
        severity: warning
      receiver: 'warning-alerts'
      repeat_interval: 30m

    # Info alerts - daily digest
    - match:
        severity: info
      receiver: 'info-alerts'
      repeat_interval: 24h

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://host.docker.internal:3000/api/monitoring/webhook'
        send_resolved: true

  - name: 'critical-alerts'
    email_configs:
      - to: 'admin@smeta360.com'
        subject: 'CRITICAL: {{ .GroupLabels.service }} Alert'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary}}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          Severity: {{ .Labels.severity }}
          {{ end }}
    webhook_configs:
      - url: 'http://host.docker.internal:3000/api/monitoring/webhook'
        send_resolved: true
    # Slack integration (optional)
    slack_configs:
      - api_url: 'YOUR_SLACK_WEBHOOK_URL'
        channel: '#alerts-critical'
        title: 'CRITICAL Alert: {{ .GroupLabels.service }}'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

  - name: 'warning-alerts'
    email_configs:
      - to: 'dev-team@smeta360.com'
        subject: 'WARNING: {{ .GroupLabels.service }} Alert'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary}}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          Severity: {{ .Labels.severity }}
          {{ end }}
    slack_configs:
      - api_url: 'YOUR_SLACK_WEBHOOK_URL'
        channel: '#alerts-warning'
        title: 'Warning: {{ .GroupLabels.service }}'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

  - name: 'info-alerts'
    email_configs:
      - to: 'monitoring@smeta360.com'
        subject: 'INFO: {{ .GroupLabels.service }} Daily Report'
        body: |
          Daily Summary:
          {{ range .Alerts }}
          - {{ .Annotations.summary}}
          {{ end }}

inhibit_rules:
  # Inhibit warning alerts if critical alert is firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['service', 'alertname']

  # Inhibit database query alerts if database is down
  - source_match:
      alertname: 'DatabaseConnectionFailed'
    target_match_re:
      alertname: 'SlowDatabaseQueries|DatabaseQueryFailures'
    equal: ['service']